// Examples and usage text per CLI flag, keyed by clap long name.
pub(super) const FLAG_META: &[(&str, &str, &str, &str)] = &[
    // Replace
    (
        "replace",
        "--replace old --with new",
        "Input:  photo_001.jpg\nOutput: image_001.jpg",
        "Replace",
    ),
    ("with", "", "", "Replace"),
    (
        "replace_case_sensitive",
        "--replace Photo --with Image --replace-case-sensitive",
        "Input:  Photo.jpg, photo.jpg\nOutput: Image.jpg, photo.jpg   (only 'Photo' matched)",
        "Replace",
    ),
    (
        "replace_first",
        "--replace a --with x --replace-first",
        "Input:  a-b-a.txt\nOutput: x-b-a.txt",
        "Replace",
    ),
    // Regex
    (
        "regex_match",
        "--regex-match IMG_\\\\d+_(\\\\d+) --regex-replace vacation_$1",
        "Input:  IMG_2024_001.jpg\nOutput: vacation_001.jpg",
        "Regex",
    ),
    ("regex_replace", "", "", "Regex"),
    (
        "regex_full_name",
        "--regex-match \\.txt$ --regex-replace .md --regex-full-name",
        "Input:  report.txt\nOutput: report.md",
        "Regex",
    ),
    // Case
    (
        "case_name",
        "--case-name title",
        "Input:  hello_world.txt\nOutput: Hello_world.txt",
        "Case",
    ),
    // case_ext removed — use Extension section instead
    // Remove
    (
        "remove_first",
        "--remove-first 4",
        "Input:  IMG_001.jpg\nOutput: 001.jpg",
        "Remove",
    ),
    (
        "remove_last",
        "--remove-last 3",
        "Input:  document_v2.txt\nOutput: document.txt",
        "Remove",
    ),
    (
        "remove_from",
        "--remove-from 5 --remove-to 8",
        "Input:  IMG_2024_001.jpg\nOutput: IMG_001.jpg",
        "Remove",
    ),
    ("remove_to", "", "", "Remove"),
    (
        "remove_chars",
        "--remove-chars '_-'",
        "Input:  hello_-world.txt\nOutput: helloworld.txt",
        "Remove",
    ),
    (
        "remove_words",
        "--remove-words 'the final'",
        "Input:  the_final_report.txt\nOutput: report.txt",
        "Remove",
    ),
    (
        "remove_digits",
        "--remove-digits",
        "Input:  photo123_456.jpg\nOutput: photo_.jpg",
        "Remove",
    ),
    (
        "remove_symbols",
        "--remove-symbols",
        "Input:  hello!_world%^.txt\nOutput: hello_world.txt",
        "Remove",
    ),
    (
        "trim",
        "--trim",
        "Input:  '  hello.txt  '\nOutput: hello.txt",
        "Remove",
    ),
    (
        "double_spaces",
        "--double-spaces",
        "Input:  'hello    world.txt'\nOutput: 'hello world.txt'",
        "Remove",
    ),
    (
        "remove",
        "--remove accents --remove digits --remove symbols",
        "Input:  hélLo_123%$.txt\nOutput: hLLo.txt",
        "Remove",
    ),
    (
        "remove_lead_dots",
        "--remove-lead-dots single",
        "Removes leading dots from filenames.",
        "Remove",
    ),
    (
        "remove_all_chars",
        "--remove-all-chars",
        "Removes all characters in the name part, leaving extension intact.",
        "Remove",
    ),
    (
        "crop",
        "--crop before:prefix --crop after:suffix",
        "Input:  prefix_stuff_suffix.jpg\nOutput: _stuff_.jpg",
        "Remove",
    ),
    // Add
    (
        "add_prefix",
        "--add-prefix vacation_",
        "Input:  beach.jpg\nOutput: vacation_beach.jpg",
        "Add",
    ),
    (
        "add_suffix",
        "--add-suffix _final",
        "Input:  report.txt\nOutput: report_final.txt",
        "Add",
    ),
    (
        "add_insert",
        "--add-insert _ --add-at 6",
        "Input:  helloworld.txt\nOutput: hello_world.txt",
        "Add",
    ),
    ("add_at", "", "", "Add"),
    (
        "add_word_space",
        "--add-word-space",
        "Input:  MyVacationPhotos.jpg\nOutput: My Vacation Photos.jpg",
        "Add",
    ),
    (
        "add_dirname",
        "--add-dirname --dirname-sep -",
        "Input:  photos/sunset.jpg\nOutput: photos-sunset.jpg",
        "Add",
    ),
    ("dirname_sep", "", "", "Add"),
    ("dirname_pos", "", "", "Add"),
    ("dirname_level", "", "", "Add"),
    (
        "add_date",
        "--add-date YYYY-MM-DD",
        "Input:  note.txt\nOutput: 2024-01-15_note.txt",
        "Add",
    ),
    (
        "date_position",
        "--date-position suffix",
        "Place the date at the end instead of the beginning.",
        "Add",
    ),
    (
        "add_file_date",
        "--add-file-date YYYYMMDD",
        "Input:  report.docx\nOutput: report_20240115.docx",
        "Add",
    ),
    // Numbering
    (
        "numbering_mode",
        "--numbering-mode prefix --numbering-pad 3 --numbering-start 1",
        "Input:  beach.jpg, sunset.jpg\nOutput: 001_beach.jpg, 002_sunset.jpg",
        "Numbering",
    ),
    ("numbering_start", "", "", "Numbering"),
    ("numbering_increment", "", "", "Numbering"),
    ("numbering_pad", "", "", "Numbering"),
    ("numbering_sep", "", "", "Numbering"),
    (
        "numbering_source",
        "--numbering-source date",
        "Sort files by modification date before assigning numbers.",
        "Numbering",
    ),
    (
        "numbering_at",
        "--numbering-at 5",
        "Insert numbering at character position 5 in the filename.",
        "Numbering",
    ),
    (
        "numbering_break",
        "--numbering-break 3",
        "Reset numbering every 3 files.",
        "Numbering",
    ),
    (
        "numbering_restart_folder",
        "--numbering-restart-folder",
        "Restart numbering for each folder when renaming recursively.",
        "Numbering",
    ),
    (
        "numbering_type",
        "--numbering-type alpha --numbering-case lower",
        "Use alphabetical numbering (a, b, c...) instead of decimal.",
        "Numbering",
    ),
    (
        "numbering_case",
        "--numbering-type roman --numbering-case upper",
        "Use uppercase Roman numerals (I, II, III...).",
        "Numbering",
    ),
    // Extension
    (
        "extension",
        "--extension .md",
        "Input:  readme.txt\nOutput: readme.md",
        "Extension",
    ),
    (
        "extension_add",
        "--extension-add .bak",
        "Input:  file.txt\nOutput: file.txt.bak",
        "Extension",
    ),
    (
        "extension_remove",
        "--extension-remove",
        "Input:  notes.txt\nOutput: notes",
        "Extension",
    ),
    ("extension_mode", "", "", "Extension"),
    (
        "extension_add_if_missing",
        "--extension-add-if-missing .md",
        "Input:  README, INSTALL.md\nOutput: README.md, INSTALL.md",
        "Extension",
    ),
    // Part
    (
        "move_part",
        "--move-part 1:3:5",
        "Input:  ABCDEFG\nOutput: DEFABCG   (chars 1-3 moved to position 5)",
        "Part",
    ),
    (
        "copy_part",
        "--copy-part 1:3:5",
        "Input:  ABCDEFG\nOutput: ABCDEFG   (chars 1-3 also copied to position 5)",
        "Part",
    ),
    // Sorting
    (
        "sort",
        "--sort date",
        "Process files oldest first. Affects numbering order and preview order.",
        "Sorting",
    ),
    (
        "exclude_regex",
        "--exclude-regex \\.bak$",
        "Skips any .bak files so they are not renamed.",
        "Sorting",
    ),
    // Filters
    ("filter_mode", "", "", "Filters"),
    ("min_name_len", "", "", "Filters"),
    ("max_name_len", "", "", "Filters"),
    ("min_path_len", "", "", "Filters"),
    ("max_path_len", "", "", "Filters"),
    ("filter_attr", "", "", "Filters"),
    (
        "filter_files",
        "--filter-files",
        "Only show files (not folders).",
        "Filters",
    ),
    (
        "filter_folders",
        "--filter-folders",
        "Only show folders (not files).",
        "Filters",
    ),
    (
        "filter_hidden",
        "--filter-hidden",
        "Include hidden files in the listing.",
        "Filters",
    ),
    (
        "filter_subfolders",
        "--filter-subfolders",
        "Recursively include subfolder contents.",
        "Filters",
    ),
    (
        "filter_level",
        "--filter-level 3",
        "Maximum nesting depth when recursing.",
        "Filters",
    ),
    (
        "filter_use_regex",
        "--filter-use-regex",
        "Treat filter patterns as regular expressions.",
        "Filters",
    ),
    (
        "filter_match_case",
        "--filter-match-case",
        "Case-sensitive filter matching.",
        "Filters",
    ),
    // Safety
    (
        "dry_run",
        "--dry-run --add-prefix vacation_",
        "Shows what would change without touching files. No risk to run this.",
        "Safety",
    ),
    ("verbose", "", "", "Safety"),
    (
        "output_dir",
        "--output-dir ./renamed --copy-mode",
        "Keeps originals in place, puts renamed copies in ./renamed.",
        "Safety",
    ),
    ("copy_mode", "", "", "Safety"),
    (
        "move_mode",
        "--move --output-dir ./out",
        "Moves originals into the output-dir instead of copying (copy is the default).",
        "Safety",
    ),
    (
        "overwrite",
        "proceed --overwrite",
        "Overwrite existing target files (applies to all collisions, skips the prompt). A collision involving a folder on either side is never overwritten or merged and is skipped.",
        "Safety",
    ),
    (
        "skip",
        "proceed --skip",
        "Skip existing target files (applies to all collisions, skips the prompt).",
        "Safety",
    ),
    (
        "undo_file",
        "--undo-file undo.json",
        "Record the successful in-place renames to a JSON file for 'awara --apply-undo'. Copy / Move to Location transfers are not recorded.",
        "Safety",
    ),
    ("stop_on_error", "", "", "Safety"),
    ("recursive", "", "", "Safety"),
    ("max_depth", "", "", "Safety"),
    (
        "preserve_timestamps",
        "--preserve-timestamps",
        "Files keep their original mtime (modification time).",
        "Safety",
    ),
    (
        "keep_structure",
        "--keep-structure --output-dir ./out",
        "Preserve directory tree when copying to output-dir.",
        "Safety",
    ),
    (
        "set_attributes",
        "--set-attributes readonly,hidden",
        "Makes renamed files read-only and hidden.",
        "Safety",
    ),
    (
        "set_created",
        "--set-created current|taken|delta:+3600|copy-from:modified|2024-01-15 12:00:00[ PM]",
        "Assign a specific creation time to renamed files. Local time; AM/PM accepted; invalid values are rejected.",
        "Safety",
    ),
    (
        "set_modified",
        "--set-modified current|taken|delta:-3600|copy-from:created|2024-01-15 12:00:00[ PM]",
        "Assign a specific modification time to renamed files. Local time; AM/PM accepted; invalid values are rejected.",
        "Safety",
    ),
    (
        "set_accessed",
        "--set-accessed current|taken|delta:0|copy-from:created|2024-01-15 12:00:00[ PM]",
        "Assign a specific access time to renamed files. Local time; AM/PM accepted; invalid values are rejected.",
        "Safety",
    ),
    (
        "save_preset",
        "save-preset my-config.json",
        "Save setup: save-preset my-config.json",
        "Safety",
    ),
    (
        "load_preset",
        "load-preset my-config.json",
        "Load later: load-preset my-config.json *.txt",
        "Safety",
    ),
    ("swap", "", "", "Safety"),
    // Name
    (
        "name_mode",
        "--name-mode fixed",
        "Set name mode: keep/remove/fixed/reverse/pad_numbers/reformat_date.",
        "Add",
    ),
    (
        "name_value",
        "--name-mode fixed --name-value 'vacation_photo'",
        "Input:  IMG_001.jpg\nOutput: vacation_photo.jpg",
        "Add",
    ),
    // Case exception
    (
        "case_exception",
        "--case-name title --case-exception iOS",
        "Preserves 'iOS' as-is when title-casing a filename.",
        "Case",
    ),
    // Regex modes
    (
        "regex_simple",
        "--regex-match '[0-9]+' --regex-replace 'NUM' --regex-simple",
        "Simplified regex mode (no need to escape special chars).",
        "Regex",
    ),
    // Name segment
    (
        "name_segment_from",
        "--name-segment-from 1 --name-segment-to 4",
        "Extract characters 1-4 from the original name.",
        "Add",
    ),
    ("insert_meta", "", "", "Metadata"),
];
